name: Deploy to firebase

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Build and deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn -i
      - name: Build dependencies
        run: REACT_APP_ENV=development DISABLE_ESLINT_PLUGIN=true yarn build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


# name: Deploy to firebase

# on:
#   push:
#     branches: [develop]

# jobs:
#   build:
#     name: Build and deploy to Firebase
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@master
#       - name: Install dependencies
#         run: yarn -i
#       - name: Build dependencies
#         run: REACT_APP_ENV=development DISABLE_ESLINT_PLUGIN=true NODE_OPTIONS=--openssl-legacy-provider yarn build

#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
